define the ietf-schedule module in a seperate draft, move it out from this draft
boucadair/policy-based-network-acl pull request #28
Opened 2023-10-13 09:30 UTC by QiufangMa

see https://github.com/QiufangMa/ietf-schedule-yang for the new draft #17

2023-10-13 09:46 UTC, boucadair approved these changes

2023-10-13 09:52 UTC, boucadair commented
> see https://github.com/QiufangMa/ietf-schedule-yang for the new draft #17

I guess you should update the new repo setup to allow read-write github actions. 

If you struggle with that, a simple option would be to add the md file to the existing repo.

2023-10-13 12:16 UTC, QiufangMa commented
> > see https://github.com/QiufangMa/ietf-schedule-yang for the new draft #17
> 
> I guess you should update the new repo setup to allow read-write github actions.
> 
> If you struggle with that, a simple option would be to add the md file to the existing repo.

Thanks Med, I think it should be fixed now, let me know if not.

2023-10-13 12:25 UTC, QiufangMa commented
I think the schedule work should be dicussed in NETMOD, but don't have strong feelings about that, would like to learn your thoughts as well.

2023-10-13 12:51 UTC, boucadair commented
> I think the schedule work should be dicussed in NETMOD, but don't have strong feelings about that, would like to learn your thoughts as well.

The UCL will have a normative dependency on the schedule module. It should be normal to maintain this in opsawg. I would avoid netmod.

2023-10-13 13:58 UTC, boucadair requested changes

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +   The YANG data models in this document conform to the Network
I would remove this mention as the module is about groupings and types.

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +#  YANG Modules
```suggestion

```

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +##  The "ietf-schedule" YANG Module {#sec-schedule}
```suggestion
#  The "ietf-schedule" YANG Module {#sec-schedule}
```

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +   This document registers the following URIs in the "IETF XML Registry" {{!RFC3688}}.
```suggestion
   This document registers the following URI in the "IETF XML Registry" {{!RFC3688}}.
```

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +   This document registers the following YANG modules in the "YANG Module Names"
```suggestion
   This document registers the following YANG module in the "YANG Module Names"
```

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +   from the WG to see this model be seperately defined for wide use in scheduling context.
```suggestion
   from the OPSAWG to see this model be separately defined for wide use in scheduling context.
```

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +   The authors would like to thank Adrian Farrel, Wei Pan, Tianran Zhou and Joe Clarke
```suggestion
   The authors would like to thank Adrian Farrel, Wei Pan, Tianran Zhou and Joe Clarke
```
```suggestion
   Thanks to Adrian Farrel, Wei Pan, Tianran Zhou, and Joe Clarke
```

2023-10-13 13:58 UTC, boucadair commented on draft-ma-netmod-schedule-yang.md
> +   for their valuable comments and great input to this work.
```suggestion
   for their valuable comments and inputs to this work.
```

2023-10-13 13:58 UTC, boucadair commented on draft-ietf-opsawg-ucl-acl.md
> +   module in <!--to add a reference-->. It also augments the IETF ACL YANG module defined in {{!RFC8519}}.
Will need to add a normative reference as well.

2023-10-16 05:14 UTC, boucadair requested changes

2023-10-16 05:14 UTC, boucadair commented on draft-ma-opsawg-schedule-yang.md
> +   this document defines a common schedule YANG module which is
```suggestion
   This document defines a common schedule YANG module which is
```

2023-10-16 05:14 UTC, boucadair commented on draft-ma-opsawg-schedule-yang.md
> +   services or resources based on date and time.
```suggestion
   services, or resources based on date and time.
```

2023-10-16 05:14 UTC, boucadair commented on draft-ma-opsawg-schedule-yang.md
> +   This document uses the YANG terminology defined in Section 3 of {{!RFC7950}}.
```suggestion
   
```

2023-10-16 05:14 UTC, boucadair commented on draft-ma-opsawg-schedule-yang.md
> +
```suggestion
Also, this document uses the YANG terminology defined in {{Section 3 of !RFC7950}}.

```

2023-10-16 05:14 UTC, boucadair commented on draft-ma-opsawg-schedule-yang.md
> +   {{?RFC5545}}. The authors might consider to define more formats in future revisions.
```suggestion
   {{?RFC5545}}. Other formats may be considered in future revisions.
```

2023-10-16 06:17 UTC, merged