update schedule YANG data model to meet TVR requirments
boucadair/policy-based-network-acl pull request #91
Opened 2024-04-16 07:24 UTC by QiufangMa

During the IETF 119 discussion with the authors of I-D. tvr-schedule-yang, they wish a machine-readable grouping without the time zone identifier parameter, and the duration value needs to be in units of seconds. This update is to incorporate the requirements and keep the definition modular at the same time.

Let me know if you have different thoughts on this.

2024-04-16 07:53 UTC, boucadair requested changes
It is OK to have both with and without TZ. Thanks.

2024-04-16 07:53 UTC, boucadair commented on yang/ietf-schedule.yang
> +  grouping recurrence-TZ {
```suggestion
  grouping recurrence-with-time-zone {
```

2024-04-16 07:53 UTC, boucadair commented on yang/ietf-schedule.yang
> +  grouping recurrence-UTC {
```suggestion
  grouping recurrence-utc {
```

2024-04-16 07:53 UTC, boucadair commented on yang/ietf-schedule.yang
> +  grouping recurrence-UTC-with-date-times {
```suggestion
  grouping recurrence-utc-with-date-times {
```

2024-04-16 07:53 UTC, boucadair commented on yang/ietf-schedule.yang
> +    uses recurrence-UTC;
```suggestion
    uses recurrence-utc;
```

2024-04-16 07:53 UTC, boucadair commented on yang/ietf-schedule.yang
> +  grouping recurrence-TZ-with-date-times {
```suggestion
  grouping recurrence-time-zone-with-date-times {
```

2024-04-16 07:53 UTC, boucadair commented on yang/ietf-schedule.yang
> +    uses recurrence-TZ;
```suggestion
    uses recurrence-time-zone;
```

2024-04-16 07:53 UTC, boucadair commented on yang/ietf-schedule.yang
> +    uses recurrence-TZ-with-date-times;
```suggestion
    uses recurrence-time-zone-with-date-times;
```

2024-04-16 08:50 UTC, QiufangMa commented
> It is OK to have both with and without TZ. Thanks.

Sure, all comments fixed.

2024-04-17 19:38 UTC, boucadair approved these changes

2024-04-17 19:39 UTC, merged